apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: lab3
  labels:
    app: employees
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 81
  selector:
    app: employees